 TUSER
 아이디   문자(20)  필수입력  중복방지
 이름     문자(30)  필수입력
 이메일   문자(320) 중복방지
 
 CREATE TABLE  TUSER  (
 USERID     VARCHAR2(20)   NOT NULL PRIMARY KEY,
 USERNAME   VARCHAR2(30)   NOT NULL,
 EMAIL      VARCHAR2(320)  UNIQUE
 );
 
 샘플데이터 5개
 INSERT  INTO  TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY' , '스카이','SKY@GREEN.COM');
 INSERT  INTO  TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY2','스카이2','SKY2@GREEN.COM');
 INSERT  INTO  TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY3','스카이3','SKY3@GREEN.COM');
 INSERT  INTO  TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY4','스카이4','SKY4@GREEN.COM');
 INSERT  INTO  TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY5','스카이5','SKY5@GREEN.COM');
 COMMIT;
 
 SELECT * FROM TUSER;
 
 SELECT * FROM TUSER  WHERE  USERID = 'SKY';
 
 
-----------------------------------------------------------------------------------
-- TMEM
회원관리
번호     숫자(6)   기본키    자동증가
이름     문자(30)  필수입력
아이디   문자(20)  필수입력  중복방지
암호     문자(20)  필수입력
이메일   문자(320) 중복방지   
가입일   날짜      기본값    오늘

 CREATE TABLE  TMEM  (
 USERNUM    NUMBER(6)      PRIMARY KEY,
 USERNAME   VARCHAR2(30)   NOT NULL,
 USERID     VARCHAR2(20)   NOT NULL  UNIQUE,
 USERPWD    VARCHAR2(20)   NOT NULL,
 EMAIL      VARCHAR2(320)  UNIQUE,
 INDATE     DATE           DEFAULT SYSDATE
 );
 
CREATE SEQUENCE SEQ_USERNUM;

INSERT INTO TMEM VALUES (SEQ_USERNUM.NEXTVAL, '스카이',  'SKY' , '1234', 'SKY@GREEN.COM', SYSDATE);
INSERT INTO TMEM VALUES (SEQ_USERNUM.NEXTVAL, '스카이2', 'SKY2', '1234', 'SKY2@GREEN.COM', SYSDATE);
INSERT INTO TMEM VALUES (SEQ_USERNUM.NEXTVAL, '스카이3', 'SKY3', '1234', 'SKY3@GREEN.COM', SYSDATE);
INSERT INTO TMEM VALUES (SEQ_USERNUM.NEXTVAL, '스카이4', 'SKY4', '1234', 'SKY4@GREEN.COM', SYSDATE);
INSERT INTO TMEM VALUES (SEQ_USERNUM.NEXTVAL, '스카이5', 'SKY5', '1234', 'SKY5@GREEN.COM', SYSDATE);
COMMIT;

SELECT SEQ_USERNUM.CURRVAL FROM DUAL;
SELECT SEQ_USERNUM.NEXTVAL FROM DUAL;

